# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0016_auto_20181109_0023'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article2tag',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='article2tag',
            name='article',
        ),
        migrations.RemoveField(
            model_name='article2tag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='tage',
            field=models.ManyToManyField(to='repository.Tag', verbose_name='所属标签'),
        ),
        migrations.DeleteModel(
            name='Article2Tag',
        ),
    ]
