# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0018_auto_20181110_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tage',
        ),
    ]
