# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0020_article_tage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tage',
            new_name='tags',
        ),
    ]
